### PR TITLE
[i18n] - [l10n] > pot + French translations

### PR DESCRIPTION
**Pull request by fxbenard**

### CODE REVIEW

**Comment by fxbenard** [comment]
Hey, can you consider my PR. I have user asking for it and a post on stand by: https://fxbenard.com/traductions/edd-sale-price/
Thanks

**Comment by JeroenSormani** [comment]
Than you for translating the plugin.

I usually don't update the plugin for translations only, but might going to do that with EDD Sale Price as there isn't much to update further.

**Comment by fxbenard** [comment]
Thanks, looking forward to see v1.0.2 release now.
For me a translation update is as much important as any other updates. Accessibility is a priority, and l10n is part of it!

**Comment by JeroenSormani** [comment]
@fxbenard Finally pushed the update for the French language ;-) Sorry it took so long.

**Pull request merged**
